### ISSUE TITLE
Integration with HA

### ISSUE THREAD

**Issue by f0b04707** [taarskog/pySOMweb#1]
Hi !

Thanks for your work on that package !

I'm interested to integrate SOMweb with HA but I'm not sure where to find the extension.

Kind regards,
WM

**Comment by taarskog** [comment]
Hi,

I've yet to send a pull request to the HA-team. Still some work and testing required on the config flow. If you want to test my current version as a custom component do this:

1. [Download](https://downgit.github.io/#/home?url=https://github.com/taarskog/home-assistant-core/tree/add-somweb-cover-platform/homeassistant/components/somweb) the latest version of the [component](https://github.com/taarskog/home-assistant-core/tree/add-somweb-cover-platform/homeassistant/components/somweb).
2. Extract the file contents under `custom_components`
2. EITHER test the config flow by restarting the server and add the SOMweb integration through the user interface (not finished so bugs adding the integration should be expected).
3.  OR add the following to `configuration.yaml` with your somweb UDI and login details before restarting the server:
````yml
cover:
  - platform: somweb
    id: <SOMweb UDI>
    username: <username>
    password: <pwd>
````

Feedback on the experience with my integration is appreciated.

-Trond

**Comment by f0b04707** [comment]
Hi !

Thanks for the reply. I'm still waiting for the SOMweb to arrive, then I'll test the integration and give a feedback.

Regards,

WM

**Comment by Thapingu** [comment]
I was thinking about creating this myself as a first phyton component for HA.. I'll for sure try this out :) Hope it get's published! I've seen so many people using somWeb via IFTTT for HA, this component would solve that "problem"..
