### ISSUE TITLE
As a Home Assistant component - a super small fix is needed!

### ISSUE THREAD

**Issue by Thapingu** [taarskog/pySOMweb#2]
Hi, to make this work as a Home Assistant component - ref: https://github.com/taarskog/home-assistant-core/tree/add-somweb-cover-platform/homeassistant/components/somweb 

You only need to add "version" tag to your manifest.json. Else you'll get: 
> WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration. -- It will not load in HASSIO..

--> Introdused in: Home Assistant 2021.6 --> Custom Components must have version in manifest.json to work!

G.ex:

```
{
    "domain": "somweb",
    "name": "SOMMER (SOMweb)",
    "documentation": "https://github.com/taarskog/home-assistant-core/tree/add-somweb-cover-platform/",
    "config_flow": true,
    "dependencies": [],
    "homeassistant": "2021.8.8",
    "version": "v1.0",
    "codeowners": [
        "@taarskog"
    ],
    "requirements": [
        "somweb==1.0.0"
    ]
}

```

I could not get your "config_flow": true, part to work (but can see it's almost done, but using it the manuel way worked like a charm!
```
cover:
  - platform: somweb
    id: <SOMweb UDI>
    username: <username>
    password: <pwd>
```

**My feed back running HASSIO 2021.8.8 (with the tweeks above)**
**Status:** open/closed --> **works!**
**Action:** Open / Close --> **works!**
_Using the Harmonie Base+ (S9080)_ 

Hope you complete this HASSIO component! It works like a charm! Lots of people asking about this integration :)

Best Regards
Inge-Andre 
_(Vet hvem du er gjennom Dynamics 365 miljøet i Norge :P)_

**Comment by taarskog** [comment]
Hi Inge-Andre,

Thanks for the feedback. I've had the version fixed in my local branch for a while. Not gotten around to committing. Now that I know there are more people than me using this thing I will prioritize doing that and fixing the flow.

Need to ensure that I follow the HA-guidelines and hopefully they'll accept my pull request so this becomes an official integration.

-Trond
(om du fortsatt er i D365-miljøet så er det ikke umulig vi snart trefffes igjen ;-))

**Comment by SilverXXX** [comment]
Hi, 
is this published somewhere as a custom repository for home assistant?
I can make one myself, with your permission

**Comment by taarskog** [comment]
Unfortunately you still need to add it manually as a custom component. Hope to be able to create a pull request to home assistant during Christmas. Some work still remains before I'm ready for that...

Feel free to create a custom repo, but appreciate that you leave the pull request towards the home assistant repo to me.

**Comment by SilverXXX** [comment]
Sorry, i meant a custom repo for home assistant using [HACS](https://hacs.xyz/) which support custom integrations (with some limits, for what i know) , i should have been more explicit.
Of course i would leave the pull request to you.

**Comment by taarskog** [comment]
All good. I assumed you were thinking of HACS, just wanted to make sure that you did not pull towards HA.

Since I maintain the Python library I'd like to control the integration code on the HA-side as well - makes it a lot easier to maintain if this is to become an official integration...

**Comment by SilverXXX** [comment]
I understand, having it in a custom repo would mostly be for testing purpose.

I do still need to set a few things on the hardware side, but i should be able to try it out

**Comment by SilverXXX** [comment]
Here is the repo https://github.com/SilverXXX/home-assistant-somweb
Just in case, if you need it or you wish for some modifications.
readme and info are minimals, but it works in HA.
Like @Thapingu i did manual configuration, but it seems to work well

**Comment by taarskog** [comment]
Now available through HACS (https://github.com/taarskog/home-assistant-component-somweb)
