### ISSUE TITLE
Local access?

### ISSUE THREAD

**Issue by Phhere** [taarskog/pySOMweb#3]
Have you tried to use the local Webservice instead of the cloud access? 
I think it should be possible to use it.
It would be nice to have an option to use the local connection.

**Comment by taarskog** [comment]
Good point. Should just be a matter of allowing input of host/IP instead of the UDI.

Will add that at next update.

**Comment by daifel** [comment]
I would also be happy if local access were possible. Especially in combination with your Home Assistant component for SOMweb.

**Comment by taarskog** [comment]
Local access added in v1.2.1 1eb6b1d. Update to Home Assistant component will follow.
